/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */

package ScheduleSystem;

/**
 *
 * @author pantilakosalaraksa
 */
public class SubjectDetail extends javax.swing.JPanel {

    /** Creates new form subjectDetail */
    public SubjectDetail() {
        initComponents();
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">                          
    private void initComponents() {

        className = new javax.swing.JLabel();
        classIDLabel = new javax.swing.JLabel();
        classId = new javax.swing.JLabel();
        timeLabel = new javax.swing.JLabel();
        midtermLabel = new javax.swing.JLabel();
        time = new javax.swing.JLabel();
        midterm = new javax.swing.JLabel();
        finalLabel = new javax.swing.JLabel();
        finalExam = new javax.swing.JLabel();

        setBackground(new java.awt.Color(244, 252, 252));
        setMaximumSize(new java.awt.Dimension(229, 32767));

        className.setFont(new java.awt.Font("Kannada Sangam MN", 1, 18)); // NOI18N
        className.setText("Data Structure & Algorithm");

        classIDLabel.setFont(new java.awt.Font("Kannada Sangam MN", 0, 16)); // NOI18N
        classIDLabel.setText("Class ID");

        classId.setFont(new java.awt.Font("Kannada Sangam MN", 0, 14)); // NOI18N
        classId.setText("jLabel4");

        timeLabel.setFont(new java.awt.Font("Kannada Sangam MN", 0, 16)); // NOI18N
        timeLabel.setForeground(new java.awt.Color(255, 51, 51));
        timeLabel.setText("Time");

        midtermLabel.setFont(new java.awt.Font("Kannada Sangam MN", 0, 16)); // NOI18N
        midtermLabel.setText("Midterm Exam");

        time.setFont(new java.awt.Font("Kannada Sangam MN", 0, 14)); // NOI18N
        time.setText("jLabel4");

        midterm.setFont(new java.awt.Font("Kannada Sangam MN", 0, 14)); // NOI18N
        midterm.setText("jLabel4");

        finalLabel.setFont(new java.awt.Font("Kannada Sangam MN", 0, 16)); // NOI18N
        finalLabel.setText("Final Exam");

        finalExam.setFont(new java.awt.Font("Kannada Sangam MN", 0, 14)); // NOI18N
        finalExam.setText("jLabel4");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap(18, Short.MAX_VALUE)
                .addComponent(className)
                .addGap(0, 12, Short.MAX_VALUE))
            .addGroup(layout.createSequentialGroup()
                .addGap(16, 16, 16)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(classIDLabel)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(finalLabel)
                            .addComponent(midtermLabel)
                            .addComponent(timeLabel)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(6, 6, 6)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(finalExam)
                                    .addComponent(midterm)
                                    .addComponent(time)
                                    .addComponent(classId))))
                        .addGap(0, 0, Short.MAX_VALUE))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(29, 29, 29)
                .addComponent(className)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(classIDLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 21, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(classId)
                .addGap(12, 12, 12)
                .addComponent(timeLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 21, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(time)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(midtermLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 21, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(midterm)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(finalLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 21, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(finalExam)
                .addContainerGap(38, Short.MAX_VALUE))
        );
    }// </editor-fold>                        


    // Variables declaration - do not modify                     
    public javax.swing.JLabel classIDLabel;
    public javax.swing.JLabel classId;
    public javax.swing.JLabel className;
    public javax.swing.JLabel finalExam;
    public javax.swing.JLabel finalLabel;
    public javax.swing.JLabel midterm;
    public javax.swing.JLabel midtermLabel;
    public javax.swing.JLabel time;
    public javax.swing.JLabel timeLabel;
    // End of variables declaration                   

}