package ProfileSystem;

import java.util.ArrayList;

import javax.swing.DefaultListModel;
import javax.swing.JCheckBox;

import org.jdesktop.swingx.auth.UserPermissions;

/**
 *
 * @author gracekasita
 */
public class ProfilePanel extends javax.swing.JPanel {

    /**
     * Creates new form NewJPanel3
     */

    private ProfileDriver driver;
    private ArrayList<String> accomplishment;
    DefaultListModel<String> listModel = new DefaultListModel<String>();

    public ProfilePanel(ProfileDriver profileDriver) {
        this.driver = profileDriver;
        this.driver.Panel = this;
        this.driver.getPath();
        this.driver.personal = new Personal();
        this.accomplishment = new ArrayList<String>();
        initComponents();
        upload();
    }

    public void upload() {
        driver.readJSON();

        if (accomplishment != null) {
            accomplishment.removeAll(accomplishment);
        }

        listModel.clear();

        for (String a: driver.personal.accomplishment) {
            accomplishment.add(a);
            listModel.addElement(a);
        }

        this.invalidate();
        this.validate();
        this.repaint();

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">                          
    private void initComponents() {

        AccompScrollPane = new javax.swing.JScrollPane();
        jList1 = new javax.swing.JList<String>(listModel);
        TopPanel = new javax.swing.JPanel();
        ProfileLabel = new javax.swing.JLabel();
        AccompLabel = new javax.swing.JLabel();

        AccompLabel.setForeground(new java.awt.Color(255, 255, 255));

        AccompScrollPane.setViewportView(jList1);

        TopPanel.setBackground(new java.awt.Color(153, 153, 153));
        TopPanel.setForeground(new java.awt.Color(102, 102, 102));

        ProfileLabel.setFont(new java.awt.Font(".AppleSystemUIFont", 1, 18)); // NOI18N
        ProfileLabel.setText("Profile");

        javax.swing.GroupLayout TopPanelLayout = new javax.swing.GroupLayout(TopPanel);
        TopPanel.setLayout(TopPanelLayout);
        TopPanelLayout.setHorizontalGroup(
            TopPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(TopPanelLayout.createSequentialGroup()
                .addGap(39, 39, 39)
                .addComponent(ProfileLabel)
                .addContainerGap(232, Short.MAX_VALUE))
        );
        TopPanelLayout.setVerticalGroup(
            TopPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, TopPanelLayout.createSequentialGroup()
                .addContainerGap(40, Short.MAX_VALUE)
                .addComponent(ProfileLabel)
                .addGap(24, 24, 24))
        );

        AccompLabel.setFont(new java.awt.Font(".AppleSystemUIFont", 0, 14)); // NOI18N
        AccompLabel.setText("Accomplishment");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(26, 26, 26)
                .addComponent(AccompScrollPane)
                .addGap(37, 37, 37))
            .addGroup(layout.createSequentialGroup()
                .addComponent(TopPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
            .addGroup(layout.createSequentialGroup()
                .addGap(34, 34, 34)
                .addComponent(AccompLabel)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addComponent(TopPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(29, 29, 29)
                .addComponent(AccompLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 17, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(AccompScrollPane, javax.swing.GroupLayout.PREFERRED_SIZE, 260, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(36, Short.MAX_VALUE))
        );
    }// </editor-fold>                        


    // Variables declaration - do not modify                     
    private javax.swing.JLabel AccompLabel;
    private javax.swing.JScrollPane AccompScrollPane;
    private javax.swing.JLabel ProfileLabel;
    private javax.swing.JPanel TopPanel;
    private javax.swing.JList<String> jList1;
    // End of variables declaration                   
}